"""
USAGE - This Python code generates random RGB values, creates a color from those 
        values using the "sty" module's "fg" function, and prints out the color 
        along with a message. The "generateRGB()" function generates random values 
        between 0 and 256 for the red, green, and blue components of the RGB color. 
        The "generateColour()" function takes the values generated by "generateRGB()" 
        and creates a color using the "fg" function from the "sty" module. 
        Finally, the "for" loop iterates ten times, each time generating a new 
        random color and printing it along with a message.


AUTHOR - https://github.com/Ahendrix9624/
"""
import random
from sty import fg

def generateRGB():
    red = random.randint(0, 256)
    green = random.randint(0, 256)
    blue = random.randint(0, 256)
    return red, green, blue

def generateColour(red, green, blue):
    return fg(red, green, blue)

for _ in range(10):
    red, green, blue = generateRGB()
    color = generateColour(red, green, blue)
    print(color, "I'm randomly changing colors muahhhhhahahaha")